# -*- coding: utf-8 -*-
"""pro4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GJAaSFLEb430LWcPjtZg-6FKeyqRSJtL
"""

pip install faker

from faker import Faker
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

fake = Faker()
names = [fake.name() for _ in range(1000)]

np.random.seed(42)
n = 250

data = {
    "Student_ID": np.arange(1, n+1),
    "Name": np.random.choice(names, n),
    "Gender": np.random.choice(["Male", "Female"], n),
    "Department": np.random.choice(["CSE", "IT", "ECE"], n),
    "Year": np.random.choice(["1st", "2nd", "3rd"], n),
    "Maths": np.random.randint(40, 100, n),
    "Science": np.random.randint(40, 100, n),
    "English": np.random.randint(40, 100, n),
    "Attendance": np.random.randint(50, 100, n),
    "Internal_Marks": np.random.randint(0, 25, n)
}

df = pd.DataFrame(data)

df["Total"] = df["Maths"] + df["Science"] + df["English"]
df["Average"] = df["Total"] / 3

df["Grade"] = df["Average"].apply(lambda x: "A" if x>=85 else "B" if x>=70 else "C" if x>=50 else "Fail")

df

"""data cleaning and preprocessing"""

df.info()

df.isnull().sum()

"""descriptive statistics"""

df.mean(numeric_only=True)

df.median(numeric_only=True)

df.describe()

df.mode()

df.std(numeric_only=True)

df[["Maths","Science","English"]].hist()
plt.show()

"""student performance metrics"""

df.Total

df.Average

df.Grade

"""top-performing students and low-performing"""

top_mark=df.sort_values(by = "Total", ascending=False).head(5)
top_mark

fail_students = df[df["Grade"] == "Fail"]
fail_students

"""Group-based analysis"""

df.groupby("Department")[["Maths","Science","English","Total","Average"]].mean()

df.groupby("Gender")[["Maths","Science","English","Total","Average"]].mean()

df.groupby("Year")[["Maths","Science","English","Total","Average"]].mean()

"""relationship between variables"""

import matplotlib.pyplot as plt

plt.scatter(df["Attendance"], df["Total"])
plt.title("Attendance vs Total Marks")
plt.xlabel("Attendance (%)")
plt.ylabel("Total Marks")
plt.show()

plt.scatter(df["Internal_Marks"], df["Total"])
plt.title("Internal Marks vs Total Marks")
plt.xlabel("Internal Marks")
plt.ylabel("Total Marks")
plt.show()

""" visualize the data using graphs and charts"""

import matplotlib.pyplot as plt

df.groupby("Department")["Total"].mean().plot(kind="bar")
plt.title("Department-wise Average Marks")
plt.xlabel("Department")
plt.ylabel("Average Marks")
plt.show()

df["Grade"].value_counts().plot(kind="pie", autopct="%1.1f%%")
plt.title("Grade Distribution")
plt.show()

plt.hist(df["Maths"])
plt.title("Distribution of Maths Marks")
plt.xlabel("Marks")
plt.ylabel("Number of Students")
plt.show()

plt.scatter(df["Attendance"], df["Total"])
plt.title("Attendance vs Total Marks")
plt.xlabel("Attendance")
plt.ylabel("Total Marks")
plt.show()

"""•	To derive meaningful insights and conclusions that can help in improving student performance and academic decision-making."""